version: '3.8'

services:
  postgres:
    container_name: task_manager_postgres_container
    image: postgres
    restart: always

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres

  adminer:
    container_name: task_manager_adminer_container
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - postgres

  task-manager:
    container_name: task_manager_api_container
    image: task-manager-datamola-2023:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/task-manager/app/.env
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  postgres:
    driver: bridge
